
paths:
  image_dir: "/data2/datasets/ruoguli/idl_project_datas/generated_dataset/image"
  normal_dir: "/data2/datasets/ruoguli/idl_project_datas/generated_dataset/normal"
  info_json_path: "/data2/datasets/ruoguli/idl_project_datas/generated_dataset/info_dataset.json" 
  latent_vectors_dir: "/data2/datasets/ruoguli/idl_project_datas/latent_vectors"
  checkpoint_dir: "/data2/datasets/ruoguli/idl_project_datas/checkpoints"
dataset:
  random_crop_size: null
  normalize: "PixelNormalize" 
  random_seed: 42
  val_split: 0.2
train: 
  batch_size: 1
eval:
  model: "PS_FCN" 
device: "cuda"
